import { Box, Group, Header, Text } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import { LoginBody } from "../client/components/Login";

const Home: NextPage = () => {

    return (
        <>
            <Head>
                <title>Login / Order Sort</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box pb={120}>
                <Header height={60} px="md">
                    <Group position="apart" sx={{ height: '100%' }}>
                        <Text
                            size="xl"
                            weight="bold"
                        >
                            Order Sort
                        </Text>
                    </Group>
                </Header>
            <LoginBody />
            </Box>
        </>
    );
};

export default Home;
