import { GetServerSideProps, type NextPage } from "next";
import Head from "next/head";
import { Box, Group, Header, Text, UnstyledButton } from "@mantine/core";
import { useRouter } from "next/router";
import dynamic from "next/dynamic";


const MapBody = dynamic(() => import('../client/components/Map'), {
    ssr: false,
});
const Home: NextPage = () => {


    const router = useRouter()

    return (
        <>
            <Head>
                <title>Order Sort</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box pb={120}>
                <Header height={60} px="md">
                    <Group position="apart" sx={{ height: '100%' }}>
                        <Text
                            size="xl"
                            onClick={() => router.push('/')}
                            weight="bold"
                        >
                            Order Sort
                        </Text>
                        <UnstyledButton
                            onClick={() => router.push('/map')}
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" style={{
                                height: '1.5rem',
                                width: '1.5rem',
                            }}
                            >
                                <path strokeLinecap="round" strokeLinejoin="round" d="M9 6.75V15m6-6v8.25m.503 3.498l4.875-2.437c.381-.19.622-.58.622-1.006V4.82c0-.836-.88-1.38-1.628-1.006l-3.869 1.934c-.317.159-.69.159-1.006 0L9.503 3.252a1.125 1.125 0 00-1.006 0L3.622 5.689C3.24 5.88 3 6.27 3 6.695V19.18c0 .836.88 1.38 1.628 1.006l3.869-1.934c.317-.159.69-.159 1.006 0l4.994 2.497c.317.158.69.158 1.006 0z" />
                            </svg>

                        </UnstyledButton>
                    </Group>
                </Header>
                <MapBody />
            </Box>
        </>
    );
};

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
    if (!req.cookies.login) {
        return {
            redirect: {
                destination: "/login",
                permanent: false,
            },
        };
    }

    return {
        props: {},
    };
};

export default Home;
